// Auto-generated by AI Test Assistant on 2026-06-05T06:11:37.281Z
// Target: src/utils/helpers.js

import { formatMoney, mapProductToCar } from './helpers.js';

describe('AEROTEC Helpers Test Suite', () => {
  // Test formatMoney
  it('formatMoney() should format standard price below 1B VND correctly', () => {
    const result = formatMoney(280000000);
    expect(result).toBe('280.000.000 VND');
  });

  it('formatMoney() should format prices above 1B VND with B suffix', () => {
    const result = formatMoney(1500000000);
    expect(result).toBe('1.5B VND');
  });

  it('formatMoney() should fallback to Contact for non-finite values', () => {
    expect(formatMoney(NaN)).toBe('Contact');
    expect(formatMoney(Infinity)).toBe('Contact');
  });

  // Test mapProductToCar
  it('mapProductToCar() should map database product with specific overrides', () => {
    const mockProduct = { id: 1, name: 'Apex R-7', price: 120000000 };
    const mapped = mapProductToCar(mockProduct);
    expect(mapped.name).toBe('Cánh Gió Đuôi Carbon Ép Apex');
    expect(mapped.sku).toBe('AT-APEX-WING-01');
    expect(mapped.material).toBe('Carbon Ép (Forged Carbon)');
  });
});
